Molality conversion and removing undefined enum
BHoM/Localisation_Toolkit pull request #107
Opened 2024-01-15 15:33 UTC by Martian42

### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #103 

 

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EkD9lu1u_fdJqv5CkRwt_-kBFLE3Rc4rHBai6uZ2TDLiAA?e=jYnmAR
 ### Changelog

 ### Additional comments

Undefined are removed in latest UnitsNet version.

2024-01-15 15:43 UTC, FraserGreenroyd requested changes
@Martian42 removing `undefined` is out of scope to the original issue and requires a broader discussion if UnitsNet have changed their support of `undefined` options. Can you add them back in for now and let this PR focus solely on the issue in #103

2024-01-25 10:06 UTC, Martian42 commented on Units_oM/Units_oM.csproj
> +  <ItemGroup>
Thanks Fraser, UnitsNet removed from oM in the latest push.

2024-01-26 10:14 UTC, FraserGreenroyd approved these changes
Code reviewed and looks good, great work @Martian42 😄

2024-01-26 10:14 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2024-01-26 10:16 UTC, FraserGreenroyd requested changes
Based on compliance checks

2024-01-26 10:16 UTC, FraserGreenroyd commented on Units_Engine/Convert/Molality/Molality.cs
> +        public static double ToMolality(this double molality, object unit)
```suggestion
        public static double ToMolality(this double molePerKilograms, object unit)
```

2024-01-26 10:16 UTC, FraserGreenroyd commented on Units_Engine/Convert/Molality/Molality.cs
> +            UN.QuantityValue qv = molality;
```suggestion
            if (Double.IsNaN(molePerKilograms) || Double.IsInfinity(molePerKilograms))
            {
                Compute.RecordError("Quantity is not a valid number.");
                return double.NaN;
            }

            UN.QuantityValue qv = molePerKilograms;
```

2024-01-26 10:17 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2024-01-26 10:19 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check null-handling
@BHoMBot check serialisation

2024-01-26 10:32 UTC, FraserGreenroyd approved these changes
All looks good now the compliance is passing 😄

2024-01-26 11:31 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2024-01-26 11:34 UTC, merged