Localisation_Engine: Added convert methods for Energy and Mass
BHoM/Localisation_Toolkit pull request #109
Opened 2024-02-20 15:21 UTC by Tom-Kingstone

### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #8 
 Closes #50 

 
Added methods to convert between Energy units (SI unit: Joules), and between Mass units (SI unit: Kilograms).
Also added respective enums for their units, and some more specific convert methods.

 ### Test files

 ### Changelog

 ### Additional comments

2024-02-20 15:21 UTC, Tom-Kingstone commented
@BHoMBot check copyright-compliance

2024-02-20 15:22 UTC, Tom-Kingstone commented
@BHoMBot fix copyright headers ref. 21774941735

2024-02-20 15:23 UTC, Tom-Kingstone commented
@BHoMBot check core
@BHoMBot check compliance

2024-02-20 15:28 UTC, Tom-Kingstone commented
@BHoMBot check compliance

2024-02-21 10:54 UTC, FraserGreenroyd requested changes

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/BritishThermalUnit.cs
> +        [Description("Convert SI units (joules) into british thermal units")]
```suggestion
        [Description("Convert SI units (joules) into British thermal units")]
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/BritishThermalUnit.cs
> +        [Description("Convert british thermal units into SI units (joules)")]
```suggestion
        [Description("Convert British thermal units into SI units (joules)")]
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/Energy.cs
> +        [Description("Convert a angle into SI units (joule).")]
Description needs updating as we're not converting an angle here.

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/Energy.cs
> +
```suggestion
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/MegabritishThermalUnit.cs
> +        [Description("Convert SI units (joules) into mega british thermal units")]
```suggestion
        [Description("Convert SI units (joules) into mega British thermal units")]
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/MegabritishThermalUnit.cs
> +/*
File name needs a capital B on British

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/MegabritishThermalUnit.cs
> +        [Description("Convert mega british thermal units into SI units (joules)")]
```suggestion
        [Description("Convert mega British thermal units into SI units (joules)")]
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_Engine/Convert/Mass/Mass.cs
> +
```suggestion
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_oM/Enums/Energy.cs
> +        KilobritishThermalUnit,
```suggestion
        KiloBritishThermalUnit,
```

2024-02-21 10:54 UTC, FraserGreenroyd commented on Units_oM/Enums/Energy.cs
> +        MegabritishThermalUnit,
```suggestion
        MegaBritishThermalUnit,
```

2024-02-21 18:00 UTC, FraserGreenroyd requested changes

2024-02-22 09:57 UTC, FraserGreenroyd requested changes
Nearly there @Tom-Kingstone 😉 

Also, we could do with some unit tests for the new methods please, otherwise @peterjamesnugent will be unhappy 😄

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/BritishThermalUnit.cs
> +        [Output("britishThermalUnits", "The number of british thermal units")]
```suggestion
        [Output("britishThermalUnits", "The number of British thermal units")]
```

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/BritishThermalUnit.cs
> +        [Input("britishThermalUnits", "The number of british thermal units to convert")]
```suggestion
        [Input("britishThermalUnits", "The number of British thermal units to convert")]
```

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/MegaBritishThermalUnit.cs
> +        [Output("megaBritishThermalUnits", "The number of mega british thermal units")]
```suggestion
        [Output("megaBritishThermalUnits", "The number of mega British thermal units")]
```

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Energy/MegaBritishThermalUnit.cs
> +        [Input("megaBritishThermalUnits", "The number of mega british thermal units to convert")]
```suggestion
        [Input("megaBritishThermalUnits", "The number of mega British thermal units to convert")]
```

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Mass/Mass.cs
> +        [Description("Convert a mass into SI units (kiloGram).")]
```suggestion
        [Description("Convert a mass into SI units (kilogram).")]
```

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Mass/Mass.cs
> +        [Input("kilogram", "The number of kiloGram to convert.")]
```suggestion
        [Input("kilogram", "The number of kilogram to convert.")]
```

2024-02-22 09:57 UTC, FraserGreenroyd commented on Units_Engine/Convert/Mass/Mass.cs
> +
```suggestion
```

2024-02-23 10:25 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2024-02-23 10:29 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2024-02-23 10:32 UTC, Tom-Kingstone commented
@BHoMBot check versioning
@BHoMBot check installer

2024-02-23 11:56 UTC, Tom-Kingstone commented
@BHoMBot check serialisation
@BHoMBot check null-handling

2024-02-23 12:52 UTC, FraserGreenroyd approved these changes
Everything looks good now on review, thanks @Tom-Kingstone

2024-02-23 12:52 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2024-02-23 12:53 UTC, merged